# Variables
@baseUrl = http://localhost:3333

###

# Health Check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get Rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create Room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Sala de teste qdnmioqndqoifd",
  "description": "Testandooo.... fiwnfiue"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get Questions by Room
# @name getQuestionsByRoom
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create a Question
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
  "question": "Testando criação da questão fwgghehhrth"
}